### PR TITLE
Support Ruby 2.4

### PR DESCRIPTION
**Pull request by tanaka51**
Hi,

I can't install this gem, jsonapi, on Ruby 2.4(preview1 and preview2) because Ruby 2.4 unifies Bignum and Fixnum to Integer and the json gem version 1.8 that this gem dependents on uses both classes. Now, supported version is released as 2.0.
To resolve this issue, I simply removed the json gem dependency.

Thanks.

### CODE REVIEW

**Comment by jasnow** [comment]
@tanaka51 - Does it work with preview2?

**Comment by tanaka51** [comment]
@jasnow Yes, it works on my end. (Travis CI does not support preview2 yet...

**Comment by beauby** [comment]
Thanks for the PR @tanaka51 – I think the best way around all those issues is, indeed, to remove the dependency on the `json` gem (as it does not provide much value in this gem anyway). Let's take care of it in #33, and close this PR.

**Comment by tanaka51** [comment]
@beauby Sorry for late response. I totally agree with your opinion. Thank you for reviewing my PR and :)

**Pull request closed without merging**
